// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: antifraud.proto

package antifraud

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OperationStatus - общий статус операции в банке. Разные системы переводят его в разный момент времени.
type OperationStatus int32

const (
	OperationStatus_Unknown  OperationStatus = 0
	OperationStatus_Created  OperationStatus = 1
	OperationStatus_Declined OperationStatus = 2 // На деле, тут еще и может быть заложен челлендж
	OperationStatus_Approved OperationStatus = 3
	OperationStatus_Closed   OperationStatus = 4 // реализованные системы не трогают данный статус
)

// Enum value maps for OperationStatus.
var (
	OperationStatus_name = map[int32]string{
		0: "Unknown",
		1: "Created",
		2: "Declined",
		3: "Approved",
		4: "Closed",
	}
	OperationStatus_value = map[string]int32{
		"Unknown":  0,
		"Created":  1,
		"Declined": 2,
		"Approved": 3,
		"Closed":   4,
	}
)

func (x OperationStatus) Enum() *OperationStatus {
	p := new(OperationStatus)
	*p = x
	return p
}

func (x OperationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_antifraud_proto_enumTypes[0].Descriptor()
}

func (OperationStatus) Type() protoreflect.EnumType {
	return &file_antifraud_proto_enumTypes[0]
}

func (x OperationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationStatus.Descriptor instead.
func (OperationStatus) EnumDescriptor() ([]byte, []int) {
	return file_antifraud_proto_rawDescGZIP(), []int{0}
}

type Transaction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// уникальный ключ
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// UUID транзакции из внешней системы
	TransactionId string `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	// дата и время операции, как передано источником
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// сумма транзакции
	Amount int64 `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	// валюта (RUB / USD / EUR)
	Currency string `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	// название/идентификатор магазина/сервиса
	Merchant string `protobuf:"bytes,6,opt,name=merchant,proto3" json:"merchant,omitempty"`
	// ISO-код страны (RU/US/CA)
	Country string `protobuf:"bytes,7,opt,name=country,proto3" json:"country,omitempty"`
	// uuid отправителя
	SenderId string `protobuf:"bytes,8,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	// uuid получателя
	ReceiverId *string `protobuf:"bytes,9,opt,name=receiver_id,json=receiverId,proto3,oneof" json:"receiver_id,omitempty"`
	// bic банка получателя
	Bic *string `protobuf:"bytes,10,opt,name=bic,proto3,oneof" json:"bic,omitempty"`
	// uuid банкомата
	AtmId         *string `protobuf:"bytes,11,opt,name=atm_id,json=atmId,proto3,oneof" json:"atm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_antifraud_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_antifraud_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_antifraud_proto_rawDescGZIP(), []int{0}
}

func (x *Transaction) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Transaction) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *Transaction) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Transaction) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Transaction) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Transaction) GetMerchant() string {
	if x != nil {
		return x.Merchant
	}
	return ""
}

func (x *Transaction) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Transaction) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *Transaction) GetReceiverId() string {
	if x != nil && x.ReceiverId != nil {
		return *x.ReceiverId
	}
	return ""
}

func (x *Transaction) GetBic() string {
	if x != nil && x.Bic != nil {
		return *x.Bic
	}
	return ""
}

func (x *Transaction) GetAtmId() string {
	if x != nil && x.AtmId != nil {
		return *x.AtmId
	}
	return ""
}

type CheckResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewStatus     OperationStatus        `protobuf:"varint,1,opt,name=new_status,json=newStatus,proto3,enum=antifraud.OperationStatus" json:"new_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResult) Reset() {
	*x = CheckResult{}
	mi := &file_antifraud_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResult) ProtoMessage() {}

func (x *CheckResult) ProtoReflect() protoreflect.Message {
	mi := &file_antifraud_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResult.ProtoReflect.Descriptor instead.
func (*CheckResult) Descriptor() ([]byte, []int) {
	return file_antifraud_proto_rawDescGZIP(), []int{1}
}

func (x *CheckResult) GetNewStatus() OperationStatus {
	if x != nil {
		return x.NewStatus
	}
	return OperationStatus_Unknown
}

var File_antifraud_proto protoreflect.FileDescriptor

const file_antifraud_proto_rawDesc = "" +
	"\n" +
	"\x0fantifraud.proto\x12\tantifraud\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\"\x82\x03\n" +
	"\vTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x1a\n" +
	"\bmerchant\x18\x06 \x01(\tR\bmerchant\x12\x18\n" +
	"\acountry\x18\a \x01(\tR\acountry\x12\x1b\n" +
	"\tsender_id\x18\b \x01(\tR\bsenderId\x12$\n" +
	"\vreceiver_id\x18\t \x01(\tH\x00R\n" +
	"receiverId\x88\x01\x01\x12\x15\n" +
	"\x03bic\x18\n" +
	" \x01(\tH\x01R\x03bic\x88\x01\x01\x12\x1a\n" +
	"\x06atm_id\x18\v \x01(\tH\x02R\x05atmId\x88\x01\x01B\x0e\n" +
	"\f_receiver_idB\x06\n" +
	"\x04_bicB\t\n" +
	"\a_atm_id\"H\n" +
	"\vCheckResult\x129\n" +
	"\n" +
	"new_status\x18\x01 \x01(\x0e2\x1a.antifraud.OperationStatusR\tnewStatus*S\n" +
	"\x0fOperationStatus\x12\v\n" +
	"\aUnknown\x10\x00\x12\v\n" +
	"\aCreated\x10\x01\x12\f\n" +
	"\bDeclined\x10\x02\x12\f\n" +
	"\bApproved\x10\x03\x12\n" +
	"\n" +
	"\x06Closed\x10\x042\x92\x02\n" +
	"\vOnlineCheck\x12S\n" +
	"\bInternal\x12\x16.antifraud.Transaction\x1a\x16.antifraud.CheckResult\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/internal\x12Z\n" +
	"\vSbpOutgoing\x12\x16.antifraud.Transaction\x1a\x16.antifraud.CheckResult\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/sbp-outgoing\x12R\n" +
	"\aCashOut\x12\x16.antifraud.Transaction\x1a\x16.antifraud.CheckResult\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/cash-outB\rZ\v./antifraudb\x06proto3"

var (
	file_antifraud_proto_rawDescOnce sync.Once
	file_antifraud_proto_rawDescData []byte
)

func file_antifraud_proto_rawDescGZIP() []byte {
	file_antifraud_proto_rawDescOnce.Do(func() {
		file_antifraud_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_antifraud_proto_rawDesc), len(file_antifraud_proto_rawDesc)))
	})
	return file_antifraud_proto_rawDescData
}

var file_antifraud_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_antifraud_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_antifraud_proto_goTypes = []any{
	(OperationStatus)(0),          // 0: antifraud.OperationStatus
	(*Transaction)(nil),           // 1: antifraud.Transaction
	(*CheckResult)(nil),           // 2: antifraud.CheckResult
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_antifraud_proto_depIdxs = []int32{
	3, // 0: antifraud.Transaction.created_at:type_name -> google.protobuf.Timestamp
	0, // 1: antifraud.CheckResult.new_status:type_name -> antifraud.OperationStatus
	1, // 2: antifraud.OnlineCheck.Internal:input_type -> antifraud.Transaction
	1, // 3: antifraud.OnlineCheck.SbpOutgoing:input_type -> antifraud.Transaction
	1, // 4: antifraud.OnlineCheck.CashOut:input_type -> antifraud.Transaction
	2, // 5: antifraud.OnlineCheck.Internal:output_type -> antifraud.CheckResult
	2, // 6: antifraud.OnlineCheck.SbpOutgoing:output_type -> antifraud.CheckResult
	2, // 7: antifraud.OnlineCheck.CashOut:output_type -> antifraud.CheckResult
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_antifraud_proto_init() }
func file_antifraud_proto_init() {
	if File_antifraud_proto != nil {
		return
	}
	file_antifraud_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_antifraud_proto_rawDesc), len(file_antifraud_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_antifraud_proto_goTypes,
		DependencyIndexes: file_antifraud_proto_depIdxs,
		EnumInfos:         file_antifraud_proto_enumTypes,
		MessageInfos:      file_antifraud_proto_msgTypes,
	}.Build()
	File_antifraud_proto = out.File
	file_antifraud_proto_goTypes = nil
	file_antifraud_proto_depIdxs = nil
}
