// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: kafka.proto

package kafka_core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransactionType int32

const (
	// Неизвестно
	TransactionType_Unknown TransactionType = 0
	// Внутренний перевод
	TransactionType_Internal TransactionType = 1
	// Внесение налички
	TransactionType_CashIn TransactionType = 2
	// Снятие нала
	TransactionType_CashOut TransactionType = 3
	// Перевод по сбп
	TransactionType_SbpOutgoing TransactionType = 4
)

// Enum value maps for TransactionType.
var (
	TransactionType_name = map[int32]string{
		0: "Unknown",
		1: "Internal",
		2: "CashIn",
		3: "CashOut",
		4: "SbpOutgoing",
	}
	TransactionType_value = map[string]int32{
		"Unknown":     0,
		"Internal":    1,
		"CashIn":      2,
		"CashOut":     3,
		"SbpOutgoing": 4,
	}
)

func (x TransactionType) Enum() *TransactionType {
	p := new(TransactionType)
	*p = x
	return p
}

func (x TransactionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionType) Descriptor() protoreflect.EnumDescriptor {
	return file_kafka_proto_enumTypes[0].Descriptor()
}

func (TransactionType) Type() protoreflect.EnumType {
	return &file_kafka_proto_enumTypes[0]
}

func (x TransactionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionType.Descriptor instead.
func (TransactionType) EnumDescriptor() ([]byte, []int) {
	return file_kafka_proto_rawDescGZIP(), []int{0}
}

type TransactionCore struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// уникальный ключ
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// UUID транзакции из внешней системы
	TransactionId string `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	// дата и время операции, как передано источником
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// сумма транзакции
	Amount int64 `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	// валюта (RUB / USD / EUR)
	Currency string `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	// название/идентификатор магазина/сервиса
	Merchant string `protobuf:"bytes,6,opt,name=merchant,proto3" json:"merchant,omitempty"`
	// ISO-код страны (RU/US/CA)
	Country string `protobuf:"bytes,7,opt,name=country,proto3" json:"country,omitempty"`
	// uuid отправителя
	SenderId string `protobuf:"bytes,8,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	// uuid отправителя
	ReceiverId *string `protobuf:"bytes,9,opt,name=receiver_id,json=receiverId,proto3,oneof" json:"receiver_id,omitempty"`
	// bic банка получателя
	ReceiverBic *string `protobuf:"bytes,10,opt,name=receiver_bic,json=receiverBic,proto3,oneof" json:"receiver_bic,omitempty"`
	// uuid банкомата
	AtmId *string `protobuf:"bytes,11,opt,name=atm_id,json=atmId,proto3,oneof" json:"atm_id,omitempty"`
	// тип транзакции
	TransactionType TransactionType `protobuf:"varint,12,opt,name=transaction_type,json=transactionType,proto3,enum=kafka.TransactionType" json:"transaction_type,omitempty"`
	// ревизия
	Revision      int64 `protobuf:"varint,13,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionCore) Reset() {
	*x = TransactionCore{}
	mi := &file_kafka_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionCore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionCore) ProtoMessage() {}

func (x *TransactionCore) ProtoReflect() protoreflect.Message {
	mi := &file_kafka_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionCore.ProtoReflect.Descriptor instead.
func (*TransactionCore) Descriptor() ([]byte, []int) {
	return file_kafka_proto_rawDescGZIP(), []int{0}
}

func (x *TransactionCore) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TransactionCore) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *TransactionCore) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TransactionCore) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransactionCore) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *TransactionCore) GetMerchant() string {
	if x != nil {
		return x.Merchant
	}
	return ""
}

func (x *TransactionCore) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *TransactionCore) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *TransactionCore) GetReceiverId() string {
	if x != nil && x.ReceiverId != nil {
		return *x.ReceiverId
	}
	return ""
}

func (x *TransactionCore) GetReceiverBic() string {
	if x != nil && x.ReceiverBic != nil {
		return *x.ReceiverBic
	}
	return ""
}

func (x *TransactionCore) GetAtmId() string {
	if x != nil && x.AtmId != nil {
		return *x.AtmId
	}
	return ""
}

func (x *TransactionCore) GetTransactionType() TransactionType {
	if x != nil {
		return x.TransactionType
	}
	return TransactionType_Unknown
}

func (x *TransactionCore) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

var File_kafka_proto protoreflect.FileDescriptor

const file_kafka_proto_rawDesc = "" +
	"\n" +
	"\vkafka.proto\x12\x05kafka\x1a\x1fgoogle/protobuf/timestamp.proto\"\xff\x03\n" +
	"\x0fTransactionCore\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x1a\n" +
	"\bmerchant\x18\x06 \x01(\tR\bmerchant\x12\x18\n" +
	"\acountry\x18\a \x01(\tR\acountry\x12\x1b\n" +
	"\tsender_id\x18\b \x01(\tR\bsenderId\x12$\n" +
	"\vreceiver_id\x18\t \x01(\tH\x00R\n" +
	"receiverId\x88\x01\x01\x12&\n" +
	"\freceiver_bic\x18\n" +
	" \x01(\tH\x01R\vreceiverBic\x88\x01\x01\x12\x1a\n" +
	"\x06atm_id\x18\v \x01(\tH\x02R\x05atmId\x88\x01\x01\x12A\n" +
	"\x10transaction_type\x18\f \x01(\x0e2\x16.kafka.TransactionTypeR\x0ftransactionType\x12\x1a\n" +
	"\brevision\x18\r \x01(\x03R\brevisionB\x0e\n" +
	"\f_receiver_idB\x0f\n" +
	"\r_receiver_bicB\t\n" +
	"\a_atm_id*V\n" +
	"\x0fTransactionType\x12\v\n" +
	"\aUnknown\x10\x00\x12\f\n" +
	"\bInternal\x10\x01\x12\n" +
	"\n" +
	"\x06CashIn\x10\x02\x12\v\n" +
	"\aCashOut\x10\x03\x12\x0f\n" +
	"\vSbpOutgoing\x10\x04B\x0eZ\f./kafka_coreb\x06proto3"

var (
	file_kafka_proto_rawDescOnce sync.Once
	file_kafka_proto_rawDescData []byte
)

func file_kafka_proto_rawDescGZIP() []byte {
	file_kafka_proto_rawDescOnce.Do(func() {
		file_kafka_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kafka_proto_rawDesc), len(file_kafka_proto_rawDesc)))
	})
	return file_kafka_proto_rawDescData
}

var file_kafka_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_kafka_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_kafka_proto_goTypes = []any{
	(TransactionType)(0),          // 0: kafka.TransactionType
	(*TransactionCore)(nil),       // 1: kafka.TransactionCore
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_kafka_proto_depIdxs = []int32{
	2, // 0: kafka.TransactionCore.created_at:type_name -> google.protobuf.Timestamp
	0, // 1: kafka.TransactionCore.transaction_type:type_name -> kafka.TransactionType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_kafka_proto_init() }
func file_kafka_proto_init() {
	if File_kafka_proto != nil {
		return
	}
	file_kafka_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kafka_proto_rawDesc), len(file_kafka_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kafka_proto_goTypes,
		DependencyIndexes: file_kafka_proto_depIdxs,
		EnumInfos:         file_kafka_proto_enumTypes,
		MessageInfos:      file_kafka_proto_msgTypes,
	}.Build()
	File_kafka_proto = out.File
	file_kafka_proto_goTypes = nil
	file_kafka_proto_depIdxs = nil
}
