// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: antifraud.proto

package antifraud

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OnlineCheck_Internal_FullMethodName    = "/antifraud.OnlineCheck/Internal"
	OnlineCheck_SbpOutgoing_FullMethodName = "/antifraud.OnlineCheck/SbpOutgoing"
	OnlineCheck_CashOut_FullMethodName     = "/antifraud.OnlineCheck/CashOut"
)

// OnlineCheckClient is the client API for OnlineCheck service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OnlineCheckClient interface {
	Internal(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*CheckResult, error)
	SbpOutgoing(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*CheckResult, error)
	CashOut(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*CheckResult, error)
}

type onlineCheckClient struct {
	cc grpc.ClientConnInterface
}

func NewOnlineCheckClient(cc grpc.ClientConnInterface) OnlineCheckClient {
	return &onlineCheckClient{cc}
}

func (c *onlineCheckClient) Internal(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*CheckResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckResult)
	err := c.cc.Invoke(ctx, OnlineCheck_Internal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onlineCheckClient) SbpOutgoing(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*CheckResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckResult)
	err := c.cc.Invoke(ctx, OnlineCheck_SbpOutgoing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onlineCheckClient) CashOut(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*CheckResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckResult)
	err := c.cc.Invoke(ctx, OnlineCheck_CashOut_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OnlineCheckServer is the server API for OnlineCheck service.
// All implementations must embed UnimplementedOnlineCheckServer
// for forward compatibility.
type OnlineCheckServer interface {
	Internal(context.Context, *Transaction) (*CheckResult, error)
	SbpOutgoing(context.Context, *Transaction) (*CheckResult, error)
	CashOut(context.Context, *Transaction) (*CheckResult, error)
	mustEmbedUnimplementedOnlineCheckServer()
}

// UnimplementedOnlineCheckServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOnlineCheckServer struct{}

func (UnimplementedOnlineCheckServer) Internal(context.Context, *Transaction) (*CheckResult, error) {
	return nil, status.Error(codes.Unimplemented, "method Internal not implemented")
}
func (UnimplementedOnlineCheckServer) SbpOutgoing(context.Context, *Transaction) (*CheckResult, error) {
	return nil, status.Error(codes.Unimplemented, "method SbpOutgoing not implemented")
}
func (UnimplementedOnlineCheckServer) CashOut(context.Context, *Transaction) (*CheckResult, error) {
	return nil, status.Error(codes.Unimplemented, "method CashOut not implemented")
}
func (UnimplementedOnlineCheckServer) mustEmbedUnimplementedOnlineCheckServer() {}
func (UnimplementedOnlineCheckServer) testEmbeddedByValue()                     {}

// UnsafeOnlineCheckServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OnlineCheckServer will
// result in compilation errors.
type UnsafeOnlineCheckServer interface {
	mustEmbedUnimplementedOnlineCheckServer()
}

func RegisterOnlineCheckServer(s grpc.ServiceRegistrar, srv OnlineCheckServer) {
	// If the following call panics, it indicates UnimplementedOnlineCheckServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OnlineCheck_ServiceDesc, srv)
}

func _OnlineCheck_Internal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Transaction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnlineCheckServer).Internal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OnlineCheck_Internal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnlineCheckServer).Internal(ctx, req.(*Transaction))
	}
	return interceptor(ctx, in, info, handler)
}

func _OnlineCheck_SbpOutgoing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Transaction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnlineCheckServer).SbpOutgoing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OnlineCheck_SbpOutgoing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnlineCheckServer).SbpOutgoing(ctx, req.(*Transaction))
	}
	return interceptor(ctx, in, info, handler)
}

func _OnlineCheck_CashOut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Transaction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnlineCheckServer).CashOut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OnlineCheck_CashOut_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnlineCheckServer).CashOut(ctx, req.(*Transaction))
	}
	return interceptor(ctx, in, info, handler)
}

// OnlineCheck_ServiceDesc is the grpc.ServiceDesc for OnlineCheck service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OnlineCheck_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "antifraud.OnlineCheck",
	HandlerType: (*OnlineCheckServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Internal",
			Handler:    _OnlineCheck_Internal_Handler,
		},
		{
			MethodName: "SbpOutgoing",
			Handler:    _OnlineCheck_SbpOutgoing_Handler,
		},
		{
			MethodName: "CashOut",
			Handler:    _OnlineCheck_CashOut_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "antifraud.proto",
}
