// Code generated by MockGen. DO NOT EDIT.
// Source: settings.go
//
// Generated by this command:
//
//	mockgen -source=settings.go -destination=./mocks/rule_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	model "antifraud/internal/app/model"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRule is a mock of Rule interface.
type MockRule struct {
	ctrl     *gomock.Controller
	recorder *MockRuleMockRecorder
	isgomock struct{}
}

// MockRuleMockRecorder is the mock recorder for MockRule.
type MockRuleMockRecorder struct {
	mock *MockRule
}

// NewMockRule creates a new mock instance.
func NewMockRule(ctrl *gomock.Controller) *MockRule {
	mock := &MockRule{ctrl: ctrl}
	mock.recorder = &MockRuleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRule) EXPECT() *MockRuleMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockRule) Check(ctx context.Context, transaction *model.DomainTransaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", ctx, transaction)
	ret0, _ := ret[0].(error)
	return ret0
}

// Check indicates an expected call of Check.
func (mr *MockRuleMockRecorder) Check(ctx, transaction any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockRule)(nil).Check), ctx, transaction)
}

// ShouldRun mocks base method.
func (m *MockRule) ShouldRun(ctx context.Context, transaction *model.DomainTransaction) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShouldRun", ctx, transaction)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ShouldRun indicates an expected call of ShouldRun.
func (mr *MockRuleMockRecorder) ShouldRun(ctx, transaction any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShouldRun", reflect.TypeOf((*MockRule)(nil).ShouldRun), ctx, transaction)
}
