// Code generated by MockGen. DO NOT EDIT.
// Source: outbox.go
//
// Generated by this command:
//
//	mockgen -source=outbox.go -destination=./mocks/publisher.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	model "processing_core/generated/proc_core_db/public/model"
	reflect "reflect"

	pgx "github.com/jackc/pgx/v5"
	gomock "go.uber.org/mock/gomock"
)

// MockKafkaProducer is a mock of KafkaProducer interface.
type MockKafkaProducer struct {
	ctrl     *gomock.Controller
	recorder *MockKafkaProducerMockRecorder
	isgomock struct{}
}

// MockKafkaProducerMockRecorder is the mock recorder for MockKafkaProducer.
type MockKafkaProducerMockRecorder struct {
	mock *MockKafkaProducer
}

// NewMockKafkaProducer creates a new mock instance.
func NewMockKafkaProducer(ctrl *gomock.Controller) *MockKafkaProducer {
	mock := &MockKafkaProducer{ctrl: ctrl}
	mock.recorder = &MockKafkaProducerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKafkaProducer) EXPECT() *MockKafkaProducerMockRecorder {
	return m.recorder
}

// Produce mocks base method.
func (m *MockKafkaProducer) Produce(ctx context.Context, outbox []model.Outbox) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Produce", ctx, outbox)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Produce indicates an expected call of Produce.
func (mr *MockKafkaProducerMockRecorder) Produce(ctx, outbox any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Produce", reflect.TypeOf((*MockKafkaProducer)(nil).Produce), ctx, outbox)
}

// MockCommonDb is a mock of CommonDb interface.
type MockCommonDb struct {
	ctrl     *gomock.Controller
	recorder *MockCommonDbMockRecorder
	isgomock struct{}
}

// MockCommonDbMockRecorder is the mock recorder for MockCommonDb.
type MockCommonDbMockRecorder struct {
	mock *MockCommonDb
}

// NewMockCommonDb creates a new mock instance.
func NewMockCommonDb(ctrl *gomock.Controller) *MockCommonDb {
	mock := &MockCommonDb{ctrl: ctrl}
	mock.recorder = &MockCommonDbMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommonDb) EXPECT() *MockCommonDbMockRecorder {
	return m.recorder
}

// Transactional mocks base method.
func (m *MockCommonDb) Transactional(ctx context.Context, f func(pgx.Tx) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transactional", ctx, f)
	ret0, _ := ret[0].(error)
	return ret0
}

// Transactional indicates an expected call of Transactional.
func (mr *MockCommonDbMockRecorder) Transactional(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transactional", reflect.TypeOf((*MockCommonDb)(nil).Transactional), ctx, f)
}

// MockKafkaDb is a mock of KafkaDb interface.
type MockKafkaDb struct {
	ctrl     *gomock.Controller
	recorder *MockKafkaDbMockRecorder
	isgomock struct{}
}

// MockKafkaDbMockRecorder is the mock recorder for MockKafkaDb.
type MockKafkaDbMockRecorder struct {
	mock *MockKafkaDb
}

// NewMockKafkaDb creates a new mock instance.
func NewMockKafkaDb(ctrl *gomock.Controller) *MockKafkaDb {
	mock := &MockKafkaDb{ctrl: ctrl}
	mock.recorder = &MockKafkaDbMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKafkaDb) EXPECT() *MockKafkaDbMockRecorder {
	return m.recorder
}

// GetUnpublishedMessages mocks base method.
func (m *MockKafkaDb) GetUnpublishedMessages(ctx context.Context, tx pgx.Tx) ([]model.Outbox, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUnpublishedMessages", ctx, tx)
	ret0, _ := ret[0].([]model.Outbox)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUnpublishedMessages indicates an expected call of GetUnpublishedMessages.
func (mr *MockKafkaDbMockRecorder) GetUnpublishedMessages(ctx, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUnpublishedMessages", reflect.TypeOf((*MockKafkaDb)(nil).GetUnpublishedMessages), ctx, tx)
}

// MarkMessagesAsProcessed mocks base method.
func (m *MockKafkaDb) MarkMessagesAsProcessed(ctx context.Context, tx pgx.Tx, ids []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkMessagesAsProcessed", ctx, tx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkMessagesAsProcessed indicates an expected call of MarkMessagesAsProcessed.
func (mr *MockKafkaDbMockRecorder) MarkMessagesAsProcessed(ctx, tx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkMessagesAsProcessed", reflect.TypeOf((*MockKafkaDb)(nil).MarkMessagesAsProcessed), ctx, tx, ids)
}
