{
 "title": "antifraud Metrics",
 "panels": [
  {
   "title": "CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * rate(process_cpu_seconds_total{job=\"antifraud\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"antifraud\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "gRPC Requests per Second",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "targets": [
    {
     "expr": "sum(rate(antifraud_grpc_requests_total[1m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "gRPC Latency P50 (50th percentile)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(antifraud_grpc_request_duration_seconds_bucket[1m])) by (le, method))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "gRPC Latency P90 (90th percentile)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(antifraud_grpc_request_duration_seconds_bucket[1m])) by (le, method))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "gRPC Latency P95 (95th percentile)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(antifraud_grpc_request_duration_seconds_bucket[1m])) by (le, method))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "gRPC Errors: declined by rules [cashout]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(processing_fraud_rule_errors_total{reason=\"declined_by_af\", tx_type=\"CashOut\"}[1m])) by (rule)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "gRPC Errors: declined by rules [sbp]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(processing_fraud_rule_errors_total{reason=\"declined_by_af\", tx_type=\"SbpOutgoing\"}[1m])) by (rule)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "gRPC Errors: declined by rules [internal]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(processing_fraud_rule_errors_total{reason=\"declined_by_af\", tx_type=\"Internal\"}[1m])) by (rule)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "gRPC Errors: context canceled",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(processing_fraud_rule_errors_total{reason=\"context_canceled\"}[1m])) by (tx_type)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "gRPC Errors: other errors by rules [cashout]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(processing_fraud_rule_errors_total{reason=\"other\", tx_type=\"CashOut\"}[1m])) by (rule)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "gRPC Errors: other errors by rules [sbp]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(processing_fraud_rule_errors_total{reason=\"other\", tx_type=\"SbpOutgoing\"}[1m])) by (rule)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "gRPC Errors: other errors by rules [internal]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(processing_fraud_rule_errors_total{reason=\"other\", tx_type=\"Internal\"}[1m])) by (rule)",
     "legendFormat": "{{method}}"
    }
   ]
  }
 ]
}