{
 "title": "Processing Core Metrics",
 "panels": [
  {
   "title": "CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * rate(process_cpu_seconds_total{job=\"processing_core\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"processing_core\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "gRPC Requests per Second",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "targets": [
    {
     "expr": "sum(rate(processing_grpc_requests_total[1m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "gRPC Latency P50 (50th percentile)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(processing_grpc_request_duration_seconds_bucket[1m])) by (le, method))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "gRPC Latency P90 (90th percentile)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(processing_grpc_request_duration_seconds_bucket[1m])) by (le, method))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "gRPC Latency P95 (95th percentile)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(processing_grpc_request_duration_seconds_bucket[1m])) by (le, method))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "gRPC Errors: Limit Overflow",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(processing_grpc_errors_total{reason=\"limit_overflow\"}[1m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "gRPC Errors: fraud operations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(processing_grpc_errors_total{reason=\"fraud_operation\"}[1m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "gRPC Errors: Other",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(processing_grpc_errors_total{reason=\"other\"}[1m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "gRPC Errors: context canceled",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(processing_grpc_errors_total{reason=\"context_canceled\"}[1m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  }
 ]
}