// Code generated by MockGen. DO NOT EDIT.
// Source: cash_out_usecase.go
//
// Generated by this command:
//
//	mockgen -source=cash_out_usecase.go -destination=./mocks/cash_out_usecase_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	model "processing_core/generated/proc_core_db/public/model"
	model0 "processing_core/internal/app/model"
	reflect "reflect"

	uuid "github.com/google/uuid"
	pgx "github.com/jackc/pgx/v5"
	gomock "go.uber.org/mock/gomock"
)

// MockCashOutClientRepo is a mock of CashOutClientRepo interface.
type MockCashOutClientRepo struct {
	ctrl     *gomock.Controller
	recorder *MockCashOutClientRepoMockRecorder
	isgomock struct{}
}

// MockCashOutClientRepoMockRecorder is the mock recorder for MockCashOutClientRepo.
type MockCashOutClientRepoMockRecorder struct {
	mock *MockCashOutClientRepo
}

// NewMockCashOutClientRepo creates a new mock instance.
func NewMockCashOutClientRepo(ctrl *gomock.Controller) *MockCashOutClientRepo {
	mock := &MockCashOutClientRepo{ctrl: ctrl}
	mock.recorder = &MockCashOutClientRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCashOutClientRepo) EXPECT() *MockCashOutClientRepoMockRecorder {
	return m.recorder
}

// GetCurrentBalanceTx mocks base method.
func (m *MockCashOutClientRepo) GetCurrentBalanceTx(ctx context.Context, tx pgx.Tx, clientID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentBalanceTx", ctx, tx, clientID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentBalanceTx indicates an expected call of GetCurrentBalanceTx.
func (mr *MockCashOutClientRepoMockRecorder) GetCurrentBalanceTx(ctx, tx, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentBalanceTx", reflect.TypeOf((*MockCashOutClientRepo)(nil).GetCurrentBalanceTx), ctx, tx, clientID)
}

// UpdateBalance mocks base method.
func (m *MockCashOutClientRepo) UpdateBalance(ctx context.Context, tx pgx.Tx, clientID uuid.UUID, newBalance int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBalance", ctx, tx, clientID, newBalance)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBalance indicates an expected call of UpdateBalance.
func (mr *MockCashOutClientRepoMockRecorder) UpdateBalance(ctx, tx, clientID, newBalance any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBalance", reflect.TypeOf((*MockCashOutClientRepo)(nil).UpdateBalance), ctx, tx, clientID, newBalance)
}

// UpsertTransaction mocks base method.
func (m *MockCashOutClientRepo) UpsertTransaction(ctx context.Context, tx pgx.Tx, transaction model.TransactionsHistory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertTransaction", ctx, tx, transaction)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertTransaction indicates an expected call of UpsertTransaction.
func (mr *MockCashOutClientRepoMockRecorder) UpsertTransaction(ctx, tx, transaction any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertTransaction", reflect.TypeOf((*MockCashOutClientRepo)(nil).UpsertTransaction), ctx, tx, transaction)
}

// MockAntifraudCashOutCheck is a mock of AntifraudCashOutCheck interface.
type MockAntifraudCashOutCheck struct {
	ctrl     *gomock.Controller
	recorder *MockAntifraudCashOutCheckMockRecorder
	isgomock struct{}
}

// MockAntifraudCashOutCheckMockRecorder is the mock recorder for MockAntifraudCashOutCheck.
type MockAntifraudCashOutCheckMockRecorder struct {
	mock *MockAntifraudCashOutCheck
}

// NewMockAntifraudCashOutCheck creates a new mock instance.
func NewMockAntifraudCashOutCheck(ctrl *gomock.Controller) *MockAntifraudCashOutCheck {
	mock := &MockAntifraudCashOutCheck{ctrl: ctrl}
	mock.recorder = &MockAntifraudCashOutCheckMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAntifraudCashOutCheck) EXPECT() *MockAntifraudCashOutCheckMockRecorder {
	return m.recorder
}

// CashOutCheck mocks base method.
func (m *MockAntifraudCashOutCheck) CashOutCheck(ctx context.Context, operation *model0.CashOutDomainRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CashOutCheck", ctx, operation)
	ret0, _ := ret[0].(error)
	return ret0
}

// CashOutCheck indicates an expected call of CashOutCheck.
func (mr *MockAntifraudCashOutCheckMockRecorder) CashOutCheck(ctx, operation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CashOutCheck", reflect.TypeOf((*MockAntifraudCashOutCheck)(nil).CashOutCheck), ctx, operation)
}

// MockCashOutInterface is a mock of CashOutInterface interface.
type MockCashOutInterface struct {
	ctrl     *gomock.Controller
	recorder *MockCashOutInterfaceMockRecorder
	isgomock struct{}
}

// MockCashOutInterfaceMockRecorder is the mock recorder for MockCashOutInterface.
type MockCashOutInterfaceMockRecorder struct {
	mock *MockCashOutInterface
}

// NewMockCashOutInterface creates a new mock instance.
func NewMockCashOutInterface(ctrl *gomock.Controller) *MockCashOutInterface {
	mock := &MockCashOutInterface{ctrl: ctrl}
	mock.recorder = &MockCashOutInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCashOutInterface) EXPECT() *MockCashOutInterfaceMockRecorder {
	return m.recorder
}

// GiveMoney mocks base method.
func (m *MockCashOutInterface) GiveMoney(ctx context.Context, operation model0.Transaction) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GiveMoney", ctx, operation)
}

// GiveMoney indicates an expected call of GiveMoney.
func (mr *MockCashOutInterfaceMockRecorder) GiveMoney(ctx, operation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GiveMoney", reflect.TypeOf((*MockCashOutInterface)(nil).GiveMoney), ctx, operation)
}
