// Code generated by MockGen. DO NOT EDIT.
// Source: cash_in_usecase.go
//
// Generated by this command:
//
//	mockgen -source=cash_in_usecase.go -destination=./mocks/cash_in_usecase_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	pgx "github.com/jackc/pgx/v5"
	gomock "go.uber.org/mock/gomock"
)

// MockCommonRepo is a mock of CommonRepo interface.
type MockCommonRepo struct {
	ctrl     *gomock.Controller
	recorder *MockCommonRepoMockRecorder
	isgomock struct{}
}

// MockCommonRepoMockRecorder is the mock recorder for MockCommonRepo.
type MockCommonRepoMockRecorder struct {
	mock *MockCommonRepo
}

// NewMockCommonRepo creates a new mock instance.
func NewMockCommonRepo(ctrl *gomock.Controller) *MockCommonRepo {
	mock := &MockCommonRepo{ctrl: ctrl}
	mock.recorder = &MockCommonRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommonRepo) EXPECT() *MockCommonRepoMockRecorder {
	return m.recorder
}

// LockClient mocks base method.
func (m *MockCommonRepo) LockClient(ctx context.Context, tx pgx.Tx, clientID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockClient", ctx, tx, clientID)
	ret0, _ := ret[0].(error)
	return ret0
}

// LockClient indicates an expected call of LockClient.
func (mr *MockCommonRepoMockRecorder) LockClient(ctx, tx, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockClient", reflect.TypeOf((*MockCommonRepo)(nil).LockClient), ctx, tx, clientID)
}

// Transactional mocks base method.
func (m *MockCommonRepo) Transactional(ctx context.Context, f func(pgx.Tx) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transactional", ctx, f)
	ret0, _ := ret[0].(error)
	return ret0
}

// Transactional indicates an expected call of Transactional.
func (mr *MockCommonRepoMockRecorder) Transactional(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transactional", reflect.TypeOf((*MockCommonRepo)(nil).Transactional), ctx, f)
}

// MockCashInClientRepo is a mock of CashInClientRepo interface.
type MockCashInClientRepo struct {
	ctrl     *gomock.Controller
	recorder *MockCashInClientRepoMockRecorder
	isgomock struct{}
}

// MockCashInClientRepoMockRecorder is the mock recorder for MockCashInClientRepo.
type MockCashInClientRepoMockRecorder struct {
	mock *MockCashInClientRepo
}

// NewMockCashInClientRepo creates a new mock instance.
func NewMockCashInClientRepo(ctrl *gomock.Controller) *MockCashInClientRepo {
	mock := &MockCashInClientRepo{ctrl: ctrl}
	mock.recorder = &MockCashInClientRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCashInClientRepo) EXPECT() *MockCashInClientRepoMockRecorder {
	return m.recorder
}

// GetCurrentBalanceTx mocks base method.
func (m *MockCashInClientRepo) GetCurrentBalanceTx(ctx context.Context, tx pgx.Tx, clientID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentBalanceTx", ctx, tx, clientID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentBalanceTx indicates an expected call of GetCurrentBalanceTx.
func (mr *MockCashInClientRepoMockRecorder) GetCurrentBalanceTx(ctx, tx, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentBalanceTx", reflect.TypeOf((*MockCashInClientRepo)(nil).GetCurrentBalanceTx), ctx, tx, clientID)
}

// UpdateBalance mocks base method.
func (m *MockCashInClientRepo) UpdateBalance(ctx context.Context, tx pgx.Tx, clientID uuid.UUID, newBalance int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBalance", ctx, tx, clientID, newBalance)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBalance indicates an expected call of UpdateBalance.
func (mr *MockCashInClientRepoMockRecorder) UpdateBalance(ctx, tx, clientID, newBalance any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBalance", reflect.TypeOf((*MockCashInClientRepo)(nil).UpdateBalance), ctx, tx, clientID, newBalance)
}
