// Code generated by MockGen. DO NOT EDIT.
// Source: internal_usecase.go
//
// Generated by this command:
//
//	mockgen -source=internal_usecase.go -destination=./mocks/internal_usecase_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	model "processing_core/internal/app/model"
	reflect "reflect"

	uuid "github.com/google/uuid"
	pgx "github.com/jackc/pgx/v5"
	gomock "go.uber.org/mock/gomock"
)

// MockInternalClientRepo is a mock of InternalClientRepo interface.
type MockInternalClientRepo struct {
	ctrl     *gomock.Controller
	recorder *MockInternalClientRepoMockRecorder
	isgomock struct{}
}

// MockInternalClientRepoMockRecorder is the mock recorder for MockInternalClientRepo.
type MockInternalClientRepoMockRecorder struct {
	mock *MockInternalClientRepo
}

// NewMockInternalClientRepo creates a new mock instance.
func NewMockInternalClientRepo(ctrl *gomock.Controller) *MockInternalClientRepo {
	mock := &MockInternalClientRepo{ctrl: ctrl}
	mock.recorder = &MockInternalClientRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInternalClientRepo) EXPECT() *MockInternalClientRepoMockRecorder {
	return m.recorder
}

// AddOperationToHistory mocks base method.
func (m *MockInternalClientRepo) AddOperationToHistory(ctx context.Context, tx pgx.Tx, clientID uuid.UUID, operation model.Transaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddOperationToHistory", ctx, tx, clientID, operation)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddOperationToHistory indicates an expected call of AddOperationToHistory.
func (mr *MockInternalClientRepoMockRecorder) AddOperationToHistory(ctx, tx, clientID, operation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddOperationToHistory", reflect.TypeOf((*MockInternalClientRepo)(nil).AddOperationToHistory), ctx, tx, clientID, operation)
}

// GetCurrentBalanceTx mocks base method.
func (m *MockInternalClientRepo) GetCurrentBalanceTx(ctx context.Context, tx pgx.Tx, clientID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentBalanceTx", ctx, tx, clientID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentBalanceTx indicates an expected call of GetCurrentBalanceTx.
func (mr *MockInternalClientRepoMockRecorder) GetCurrentBalanceTx(ctx, tx, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentBalanceTx", reflect.TypeOf((*MockInternalClientRepo)(nil).GetCurrentBalanceTx), ctx, tx, clientID)
}

// UpdateBalance mocks base method.
func (m *MockInternalClientRepo) UpdateBalance(ctx context.Context, tx pgx.Tx, clientID uuid.UUID, newBalance int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBalance", ctx, tx, clientID, newBalance)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBalance indicates an expected call of UpdateBalance.
func (mr *MockInternalClientRepoMockRecorder) UpdateBalance(ctx, tx, clientID, newBalance any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBalance", reflect.TypeOf((*MockInternalClientRepo)(nil).UpdateBalance), ctx, tx, clientID, newBalance)
}

// MockAntifraudInternalCheck is a mock of AntifraudInternalCheck interface.
type MockAntifraudInternalCheck struct {
	ctrl     *gomock.Controller
	recorder *MockAntifraudInternalCheckMockRecorder
	isgomock struct{}
}

// MockAntifraudInternalCheckMockRecorder is the mock recorder for MockAntifraudInternalCheck.
type MockAntifraudInternalCheckMockRecorder struct {
	mock *MockAntifraudInternalCheck
}

// NewMockAntifraudInternalCheck creates a new mock instance.
func NewMockAntifraudInternalCheck(ctrl *gomock.Controller) *MockAntifraudInternalCheck {
	mock := &MockAntifraudInternalCheck{ctrl: ctrl}
	mock.recorder = &MockAntifraudInternalCheckMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAntifraudInternalCheck) EXPECT() *MockAntifraudInternalCheckMockRecorder {
	return m.recorder
}

// InternalCheck mocks base method.
func (m *MockAntifraudInternalCheck) InternalCheck(ctx context.Context, operation model.Transaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InternalCheck", ctx, operation)
	ret0, _ := ret[0].(error)
	return ret0
}

// InternalCheck indicates an expected call of InternalCheck.
func (mr *MockAntifraudInternalCheckMockRecorder) InternalCheck(ctx, operation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalCheck", reflect.TypeOf((*MockAntifraudInternalCheck)(nil).InternalCheck), ctx, operation)
}
