// Code generated by MockGen. DO NOT EDIT.
// Source: sbp_outgoing_usecase.go
//
// Generated by this command:
//
//	mockgen -source=sbp_outgoing_usecase.go -destination=./mocks/sbp_outgoing_usecase_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	model "processing_core/generated/proc_core_db/public/model"
	model0 "processing_core/internal/app/model"
	reflect "reflect"

	uuid "github.com/google/uuid"
	pgx "github.com/jackc/pgx/v5"
	gomock "go.uber.org/mock/gomock"
)

// MockSbpOutgoingClientRepo is a mock of SbpOutgoingClientRepo interface.
type MockSbpOutgoingClientRepo struct {
	ctrl     *gomock.Controller
	recorder *MockSbpOutgoingClientRepoMockRecorder
	isgomock struct{}
}

// MockSbpOutgoingClientRepoMockRecorder is the mock recorder for MockSbpOutgoingClientRepo.
type MockSbpOutgoingClientRepoMockRecorder struct {
	mock *MockSbpOutgoingClientRepo
}

// NewMockSbpOutgoingClientRepo creates a new mock instance.
func NewMockSbpOutgoingClientRepo(ctrl *gomock.Controller) *MockSbpOutgoingClientRepo {
	mock := &MockSbpOutgoingClientRepo{ctrl: ctrl}
	mock.recorder = &MockSbpOutgoingClientRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSbpOutgoingClientRepo) EXPECT() *MockSbpOutgoingClientRepoMockRecorder {
	return m.recorder
}

// GetCurrentBalanceTx mocks base method.
func (m *MockSbpOutgoingClientRepo) GetCurrentBalanceTx(ctx context.Context, tx pgx.Tx, clientID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentBalanceTx", ctx, tx, clientID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentBalanceTx indicates an expected call of GetCurrentBalanceTx.
func (mr *MockSbpOutgoingClientRepoMockRecorder) GetCurrentBalanceTx(ctx, tx, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentBalanceTx", reflect.TypeOf((*MockSbpOutgoingClientRepo)(nil).GetCurrentBalanceTx), ctx, tx, clientID)
}

// UpdateBalance mocks base method.
func (m *MockSbpOutgoingClientRepo) UpdateBalance(ctx context.Context, tx pgx.Tx, clientID uuid.UUID, newBalance int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBalance", ctx, tx, clientID, newBalance)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBalance indicates an expected call of UpdateBalance.
func (mr *MockSbpOutgoingClientRepoMockRecorder) UpdateBalance(ctx, tx, clientID, newBalance any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBalance", reflect.TypeOf((*MockSbpOutgoingClientRepo)(nil).UpdateBalance), ctx, tx, clientID, newBalance)
}

// UpsertTransaction mocks base method.
func (m *MockSbpOutgoingClientRepo) UpsertTransaction(ctx context.Context, tx pgx.Tx, transaction model.TransactionsHistory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertTransaction", ctx, tx, transaction)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertTransaction indicates an expected call of UpsertTransaction.
func (mr *MockSbpOutgoingClientRepoMockRecorder) UpsertTransaction(ctx, tx, transaction any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertTransaction", reflect.TypeOf((*MockSbpOutgoingClientRepo)(nil).UpsertTransaction), ctx, tx, transaction)
}

// MockAntifraudSbpOutgoingCheck is a mock of AntifraudSbpOutgoingCheck interface.
type MockAntifraudSbpOutgoingCheck struct {
	ctrl     *gomock.Controller
	recorder *MockAntifraudSbpOutgoingCheckMockRecorder
	isgomock struct{}
}

// MockAntifraudSbpOutgoingCheckMockRecorder is the mock recorder for MockAntifraudSbpOutgoingCheck.
type MockAntifraudSbpOutgoingCheckMockRecorder struct {
	mock *MockAntifraudSbpOutgoingCheck
}

// NewMockAntifraudSbpOutgoingCheck creates a new mock instance.
func NewMockAntifraudSbpOutgoingCheck(ctrl *gomock.Controller) *MockAntifraudSbpOutgoingCheck {
	mock := &MockAntifraudSbpOutgoingCheck{ctrl: ctrl}
	mock.recorder = &MockAntifraudSbpOutgoingCheckMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAntifraudSbpOutgoingCheck) EXPECT() *MockAntifraudSbpOutgoingCheckMockRecorder {
	return m.recorder
}

// SbpOutgoingCheck mocks base method.
func (m *MockAntifraudSbpOutgoingCheck) SbpOutgoingCheck(ctx context.Context, operation *model0.SbpOutgoingDomainRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SbpOutgoingCheck", ctx, operation)
	ret0, _ := ret[0].(error)
	return ret0
}

// SbpOutgoingCheck indicates an expected call of SbpOutgoingCheck.
func (mr *MockAntifraudSbpOutgoingCheckMockRecorder) SbpOutgoingCheck(ctx, operation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SbpOutgoingCheck", reflect.TypeOf((*MockAntifraudSbpOutgoingCheck)(nil).SbpOutgoingCheck), ctx, operation)
}

// MockSbpIntegrationInterface is a mock of SbpIntegrationInterface interface.
type MockSbpIntegrationInterface struct {
	ctrl     *gomock.Controller
	recorder *MockSbpIntegrationInterfaceMockRecorder
	isgomock struct{}
}

// MockSbpIntegrationInterfaceMockRecorder is the mock recorder for MockSbpIntegrationInterface.
type MockSbpIntegrationInterfaceMockRecorder struct {
	mock *MockSbpIntegrationInterface
}

// NewMockSbpIntegrationInterface creates a new mock instance.
func NewMockSbpIntegrationInterface(ctrl *gomock.Controller) *MockSbpIntegrationInterface {
	mock := &MockSbpIntegrationInterface{ctrl: ctrl}
	mock.recorder = &MockSbpIntegrationInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSbpIntegrationInterface) EXPECT() *MockSbpIntegrationInterfaceMockRecorder {
	return m.recorder
}

// ToAnotherBank mocks base method.
func (m *MockSbpIntegrationInterface) ToAnotherBank(ctx context.Context, operation model0.Transaction) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ToAnotherBank", ctx, operation)
}

// ToAnotherBank indicates an expected call of ToAnotherBank.
func (mr *MockSbpIntegrationInterfaceMockRecorder) ToAnotherBank(ctx, operation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToAnotherBank", reflect.TypeOf((*MockSbpIntegrationInterface)(nil).ToAnotherBank), ctx, operation)
}
