// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: core.proto

package core

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Core_Internal_FullMethodName    = "/core.Core/Internal"
	Core_SbpOutgoing_FullMethodName = "/core.Core/SbpOutgoing"
	Core_CashIn_FullMethodName      = "/core.Core/CashIn"
	Core_CashOut_FullMethodName     = "/core.Core/CashOut"
)

// CoreClient is the client API for Core service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoreClient interface {
	Internal(ctx context.Context, in *InternalRequest, opts ...grpc.CallOption) (*InternalResponse, error)
	SbpOutgoing(ctx context.Context, in *SbpOutgoingRequest, opts ...grpc.CallOption) (*SbpOutgoingResponse, error)
	CashIn(ctx context.Context, in *CashInRequest, opts ...grpc.CallOption) (*CashInResponse, error)
	CashOut(ctx context.Context, in *CashOutRequest, opts ...grpc.CallOption) (*CashOutResponse, error)
}

type coreClient struct {
	cc grpc.ClientConnInterface
}

func NewCoreClient(cc grpc.ClientConnInterface) CoreClient {
	return &coreClient{cc}
}

func (c *coreClient) Internal(ctx context.Context, in *InternalRequest, opts ...grpc.CallOption) (*InternalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InternalResponse)
	err := c.cc.Invoke(ctx, Core_Internal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) SbpOutgoing(ctx context.Context, in *SbpOutgoingRequest, opts ...grpc.CallOption) (*SbpOutgoingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SbpOutgoingResponse)
	err := c.cc.Invoke(ctx, Core_SbpOutgoing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) CashIn(ctx context.Context, in *CashInRequest, opts ...grpc.CallOption) (*CashInResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CashInResponse)
	err := c.cc.Invoke(ctx, Core_CashIn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) CashOut(ctx context.Context, in *CashOutRequest, opts ...grpc.CallOption) (*CashOutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CashOutResponse)
	err := c.cc.Invoke(ctx, Core_CashOut_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoreServer is the server API for Core service.
// All implementations must embed UnimplementedCoreServer
// for forward compatibility.
type CoreServer interface {
	Internal(context.Context, *InternalRequest) (*InternalResponse, error)
	SbpOutgoing(context.Context, *SbpOutgoingRequest) (*SbpOutgoingResponse, error)
	CashIn(context.Context, *CashInRequest) (*CashInResponse, error)
	CashOut(context.Context, *CashOutRequest) (*CashOutResponse, error)
	mustEmbedUnimplementedCoreServer()
}

// UnimplementedCoreServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoreServer struct{}

func (UnimplementedCoreServer) Internal(context.Context, *InternalRequest) (*InternalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Internal not implemented")
}
func (UnimplementedCoreServer) SbpOutgoing(context.Context, *SbpOutgoingRequest) (*SbpOutgoingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SbpOutgoing not implemented")
}
func (UnimplementedCoreServer) CashIn(context.Context, *CashInRequest) (*CashInResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CashIn not implemented")
}
func (UnimplementedCoreServer) CashOut(context.Context, *CashOutRequest) (*CashOutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CashOut not implemented")
}
func (UnimplementedCoreServer) mustEmbedUnimplementedCoreServer() {}
func (UnimplementedCoreServer) testEmbeddedByValue()              {}

// UnsafeCoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoreServer will
// result in compilation errors.
type UnsafeCoreServer interface {
	mustEmbedUnimplementedCoreServer()
}

func RegisterCoreServer(s grpc.ServiceRegistrar, srv CoreServer) {
	// If the following call panics, it indicates UnimplementedCoreServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Core_ServiceDesc, srv)
}

func _Core_Internal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InternalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).Internal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_Internal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).Internal(ctx, req.(*InternalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_SbpOutgoing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SbpOutgoingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).SbpOutgoing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_SbpOutgoing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).SbpOutgoing(ctx, req.(*SbpOutgoingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_CashIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CashInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).CashIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_CashIn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).CashIn(ctx, req.(*CashInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_CashOut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CashOutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).CashOut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_CashOut_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).CashOut(ctx, req.(*CashOutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Core_ServiceDesc is the grpc.ServiceDesc for Core service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Core_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "core.Core",
	HandlerType: (*CoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Internal",
			Handler:    _Core_Internal_Handler,
		},
		{
			MethodName: "SbpOutgoing",
			Handler:    _Core_SbpOutgoing_Handler,
		},
		{
			MethodName: "CashIn",
			Handler:    _Core_CashIn_Handler,
		},
		{
			MethodName: "CashOut",
			Handler:    _Core_CashOut_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "core.proto",
}
