// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: core.proto

package core

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OperationStatus - общий статус операции в банке. Разные системы переводят его в разный момент времени.
type OperationStatus int32

const (
	OperationStatus_Unknown  OperationStatus = 0
	OperationStatus_Created  OperationStatus = 1
	OperationStatus_Declined OperationStatus = 2 // На деле, тут еще и может быть заложен челлендж
	OperationStatus_Approved OperationStatus = 3
	OperationStatus_Closed   OperationStatus = 4 // реализованные системы не трогают данный статус
)

// Enum value maps for OperationStatus.
var (
	OperationStatus_name = map[int32]string{
		0: "Unknown",
		1: "Created",
		2: "Declined",
		3: "Approved",
		4: "Closed",
	}
	OperationStatus_value = map[string]int32{
		"Unknown":  0,
		"Created":  1,
		"Declined": 2,
		"Approved": 3,
		"Closed":   4,
	}
)

func (x OperationStatus) Enum() *OperationStatus {
	p := new(OperationStatus)
	*p = x
	return p
}

func (x OperationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_core_proto_enumTypes[0].Descriptor()
}

func (OperationStatus) Type() protoreflect.EnumType {
	return &file_core_proto_enumTypes[0]
}

func (x OperationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationStatus.Descriptor instead.
func (OperationStatus) EnumDescriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{0}
}

type Transaction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// уникальный ключ
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// UUID транзакции из внешней системы
	TransactionId string `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	// дата и время операции, как передано источником
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// сумма транзакции
	Amount int64 `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	// валюта (RUB / USD / EUR)
	Currency string `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	// название/идентификатор магазина/сервиса
	Merchant string `protobuf:"bytes,6,opt,name=merchant,proto3" json:"merchant,omitempty"`
	// ISO-код страны (RU/US/CA)
	Country string `protobuf:"bytes,7,opt,name=country,proto3" json:"country,omitempty"`
	// uuid отправителя
	SenderId      string `protobuf:"bytes,8,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_core_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{0}
}

func (x *Transaction) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Transaction) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *Transaction) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Transaction) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Transaction) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Transaction) GetMerchant() string {
	if x != nil {
		return x.Merchant
	}
	return ""
}

func (x *Transaction) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Transaction) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

type InternalRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// uuid проводки
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// транзакция
	Transaction *Transaction `protobuf:"bytes,2,opt,name=transaction,proto3" json:"transaction,omitempty"`
	// uuid получателя
	ReceiverId    string `protobuf:"bytes,3,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InternalRequest) Reset() {
	*x = InternalRequest{}
	mi := &file_core_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InternalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalRequest) ProtoMessage() {}

func (x *InternalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalRequest.ProtoReflect.Descriptor instead.
func (*InternalRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{1}
}

func (x *InternalRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InternalRequest) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *InternalRequest) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

type InternalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewStatus     OperationStatus        `protobuf:"varint,1,opt,name=new_status,json=newStatus,proto3,enum=core.OperationStatus" json:"new_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InternalResponse) Reset() {
	*x = InternalResponse{}
	mi := &file_core_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InternalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalResponse) ProtoMessage() {}

func (x *InternalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalResponse.ProtoReflect.Descriptor instead.
func (*InternalResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{2}
}

func (x *InternalResponse) GetNewStatus() OperationStatus {
	if x != nil {
		return x.NewStatus
	}
	return OperationStatus_Unknown
}

type SbpOutgoingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// uuid проводки
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// транзакция
	Transaction *Transaction `protobuf:"bytes,2,opt,name=transaction,proto3" json:"transaction,omitempty"`
	// uuid получателя
	ReceiverId string `protobuf:"bytes,3,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	// bic банка получателя
	Bic           string `protobuf:"bytes,4,opt,name=bic,proto3" json:"bic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SbpOutgoingRequest) Reset() {
	*x = SbpOutgoingRequest{}
	mi := &file_core_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SbpOutgoingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SbpOutgoingRequest) ProtoMessage() {}

func (x *SbpOutgoingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SbpOutgoingRequest.ProtoReflect.Descriptor instead.
func (*SbpOutgoingRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{3}
}

func (x *SbpOutgoingRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SbpOutgoingRequest) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *SbpOutgoingRequest) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

func (x *SbpOutgoingRequest) GetBic() string {
	if x != nil {
		return x.Bic
	}
	return ""
}

type SbpOutgoingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewStatus     OperationStatus        `protobuf:"varint,1,opt,name=new_status,json=newStatus,proto3,enum=core.OperationStatus" json:"new_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SbpOutgoingResponse) Reset() {
	*x = SbpOutgoingResponse{}
	mi := &file_core_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SbpOutgoingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SbpOutgoingResponse) ProtoMessage() {}

func (x *SbpOutgoingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SbpOutgoingResponse.ProtoReflect.Descriptor instead.
func (*SbpOutgoingResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{4}
}

func (x *SbpOutgoingResponse) GetNewStatus() OperationStatus {
	if x != nil {
		return x.NewStatus
	}
	return OperationStatus_Unknown
}

type CashInRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// uuid проводки
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// транзакция
	Transaction *Transaction `protobuf:"bytes,2,opt,name=transaction,proto3" json:"transaction,omitempty"`
	// uuid банкомата
	AtmId         string `protobuf:"bytes,3,opt,name=atm_id,json=atmId,proto3" json:"atm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CashInRequest) Reset() {
	*x = CashInRequest{}
	mi := &file_core_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CashInRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CashInRequest) ProtoMessage() {}

func (x *CashInRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CashInRequest.ProtoReflect.Descriptor instead.
func (*CashInRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{5}
}

func (x *CashInRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CashInRequest) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *CashInRequest) GetAtmId() string {
	if x != nil {
		return x.AtmId
	}
	return ""
}

type CashInResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewStatus     OperationStatus        `protobuf:"varint,1,opt,name=new_status,json=newStatus,proto3,enum=core.OperationStatus" json:"new_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CashInResponse) Reset() {
	*x = CashInResponse{}
	mi := &file_core_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CashInResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CashInResponse) ProtoMessage() {}

func (x *CashInResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CashInResponse.ProtoReflect.Descriptor instead.
func (*CashInResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{6}
}

func (x *CashInResponse) GetNewStatus() OperationStatus {
	if x != nil {
		return x.NewStatus
	}
	return OperationStatus_Unknown
}

type CashOutRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// uuid проводки
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// транзакция
	Transaction *Transaction `protobuf:"bytes,2,opt,name=transaction,proto3" json:"transaction,omitempty"`
	// uuid банкомата
	AtmId         string `protobuf:"bytes,3,opt,name=atm_id,json=atmId,proto3" json:"atm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CashOutRequest) Reset() {
	*x = CashOutRequest{}
	mi := &file_core_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CashOutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CashOutRequest) ProtoMessage() {}

func (x *CashOutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CashOutRequest.ProtoReflect.Descriptor instead.
func (*CashOutRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{7}
}

func (x *CashOutRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CashOutRequest) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *CashOutRequest) GetAtmId() string {
	if x != nil {
		return x.AtmId
	}
	return ""
}

type CashOutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewStatus     OperationStatus        `protobuf:"varint,1,opt,name=new_status,json=newStatus,proto3,enum=core.OperationStatus" json:"new_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CashOutResponse) Reset() {
	*x = CashOutResponse{}
	mi := &file_core_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CashOutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CashOutResponse) ProtoMessage() {}

func (x *CashOutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CashOutResponse.ProtoReflect.Descriptor instead.
func (*CashOutResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{8}
}

func (x *CashOutResponse) GetNewStatus() OperationStatus {
	if x != nil {
		return x.NewStatus
	}
	return OperationStatus_Unknown
}

var File_core_proto protoreflect.FileDescriptor

const file_core_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"core.proto\x12\x04core\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\"\x86\x02\n" +
	"\vTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x1a\n" +
	"\bmerchant\x18\x06 \x01(\tR\bmerchant\x12\x18\n" +
	"\acountry\x18\a \x01(\tR\acountry\x12\x1b\n" +
	"\tsender_id\x18\b \x01(\tR\bsenderId\"w\n" +
	"\x0fInternalRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x123\n" +
	"\vtransaction\x18\x02 \x01(\v2\x11.core.TransactionR\vtransaction\x12\x1f\n" +
	"\vreceiver_id\x18\x03 \x01(\tR\n" +
	"receiverId\"H\n" +
	"\x10InternalResponse\x124\n" +
	"\n" +
	"new_status\x18\x01 \x01(\x0e2\x15.core.OperationStatusR\tnewStatus\"\x8c\x01\n" +
	"\x12SbpOutgoingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x123\n" +
	"\vtransaction\x18\x02 \x01(\v2\x11.core.TransactionR\vtransaction\x12\x1f\n" +
	"\vreceiver_id\x18\x03 \x01(\tR\n" +
	"receiverId\x12\x10\n" +
	"\x03bic\x18\x04 \x01(\tR\x03bic\"K\n" +
	"\x13SbpOutgoingResponse\x124\n" +
	"\n" +
	"new_status\x18\x01 \x01(\x0e2\x15.core.OperationStatusR\tnewStatus\"k\n" +
	"\rCashInRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x123\n" +
	"\vtransaction\x18\x02 \x01(\v2\x11.core.TransactionR\vtransaction\x12\x15\n" +
	"\x06atm_id\x18\x03 \x01(\tR\x05atmId\"F\n" +
	"\x0eCashInResponse\x124\n" +
	"\n" +
	"new_status\x18\x01 \x01(\x0e2\x15.core.OperationStatusR\tnewStatus\"l\n" +
	"\x0eCashOutRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x123\n" +
	"\vtransaction\x18\x02 \x01(\v2\x11.core.TransactionR\vtransaction\x12\x15\n" +
	"\x06atm_id\x18\x03 \x01(\tR\x05atmId\"G\n" +
	"\x0fCashOutResponse\x124\n" +
	"\n" +
	"new_status\x18\x01 \x01(\x0e2\x15.core.OperationStatusR\tnewStatus*S\n" +
	"\x0fOperationStatus\x12\v\n" +
	"\aUnknown\x10\x00\x12\v\n" +
	"\aCreated\x10\x01\x12\f\n" +
	"\bDeclined\x10\x02\x12\f\n" +
	"\bApproved\x10\x03\x12\n" +
	"\n" +
	"\x06Closed\x10\x042\xd9\x02\n" +
	"\x04Core\x12R\n" +
	"\bInternal\x12\x15.core.InternalRequest\x1a\x16.core.InternalResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/internal\x12_\n" +
	"\vSbpOutgoing\x12\x18.core.SbpOutgoingRequest\x1a\x19.core.SbpOutgoingResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/sbp-outgoing\x12K\n" +
	"\x06CashIn\x12\x13.core.CashInRequest\x1a\x14.core.CashInResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/v1/cash/in\x12O\n" +
	"\aCashOut\x12\x14.core.CashOutRequest\x1a\x15.core.CashOutResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/cash/outB\bZ\x06./coreb\x06proto3"

var (
	file_core_proto_rawDescOnce sync.Once
	file_core_proto_rawDescData []byte
)

func file_core_proto_rawDescGZIP() []byte {
	file_core_proto_rawDescOnce.Do(func() {
		file_core_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_proto_rawDesc), len(file_core_proto_rawDesc)))
	})
	return file_core_proto_rawDescData
}

var file_core_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_core_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_core_proto_goTypes = []any{
	(OperationStatus)(0),          // 0: core.OperationStatus
	(*Transaction)(nil),           // 1: core.Transaction
	(*InternalRequest)(nil),       // 2: core.InternalRequest
	(*InternalResponse)(nil),      // 3: core.InternalResponse
	(*SbpOutgoingRequest)(nil),    // 4: core.SbpOutgoingRequest
	(*SbpOutgoingResponse)(nil),   // 5: core.SbpOutgoingResponse
	(*CashInRequest)(nil),         // 6: core.CashInRequest
	(*CashInResponse)(nil),        // 7: core.CashInResponse
	(*CashOutRequest)(nil),        // 8: core.CashOutRequest
	(*CashOutResponse)(nil),       // 9: core.CashOutResponse
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
}
var file_core_proto_depIdxs = []int32{
	10, // 0: core.Transaction.created_at:type_name -> google.protobuf.Timestamp
	1,  // 1: core.InternalRequest.transaction:type_name -> core.Transaction
	0,  // 2: core.InternalResponse.new_status:type_name -> core.OperationStatus
	1,  // 3: core.SbpOutgoingRequest.transaction:type_name -> core.Transaction
	0,  // 4: core.SbpOutgoingResponse.new_status:type_name -> core.OperationStatus
	1,  // 5: core.CashInRequest.transaction:type_name -> core.Transaction
	0,  // 6: core.CashInResponse.new_status:type_name -> core.OperationStatus
	1,  // 7: core.CashOutRequest.transaction:type_name -> core.Transaction
	0,  // 8: core.CashOutResponse.new_status:type_name -> core.OperationStatus
	2,  // 9: core.Core.Internal:input_type -> core.InternalRequest
	4,  // 10: core.Core.SbpOutgoing:input_type -> core.SbpOutgoingRequest
	6,  // 11: core.Core.CashIn:input_type -> core.CashInRequest
	8,  // 12: core.Core.CashOut:input_type -> core.CashOutRequest
	3,  // 13: core.Core.Internal:output_type -> core.InternalResponse
	5,  // 14: core.Core.SbpOutgoing:output_type -> core.SbpOutgoingResponse
	7,  // 15: core.Core.CashIn:output_type -> core.CashInResponse
	9,  // 16: core.Core.CashOut:output_type -> core.CashOutResponse
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_core_proto_init() }
func file_core_proto_init() {
	if File_core_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_proto_rawDesc), len(file_core_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_proto_goTypes,
		DependencyIndexes: file_core_proto_depIdxs,
		EnumInfos:         file_core_proto_enumTypes,
		MessageInfos:      file_core_proto_msgTypes,
	}.Build()
	File_core_proto = out.File
	file_core_proto_goTypes = nil
	file_core_proto_depIdxs = nil
}
