// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=./mocks/service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	model "processing_core/internal/app/model"
	core "processing_core/pkg/core"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSbpOutgoingOperations is a mock of SbpOutgoingOperations interface.
type MockSbpOutgoingOperations struct {
	ctrl     *gomock.Controller
	recorder *MockSbpOutgoingOperationsMockRecorder
	isgomock struct{}
}

// MockSbpOutgoingOperationsMockRecorder is the mock recorder for MockSbpOutgoingOperations.
type MockSbpOutgoingOperationsMockRecorder struct {
	mock *MockSbpOutgoingOperations
}

// NewMockSbpOutgoingOperations creates a new mock instance.
func NewMockSbpOutgoingOperations(ctrl *gomock.Controller) *MockSbpOutgoingOperations {
	mock := &MockSbpOutgoingOperations{ctrl: ctrl}
	mock.recorder = &MockSbpOutgoingOperationsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSbpOutgoingOperations) EXPECT() *MockSbpOutgoingOperationsMockRecorder {
	return m.recorder
}

// Process mocks base method.
func (m *MockSbpOutgoingOperations) Process(ctx context.Context, domainRequest *model.SbpOutgoingDomainRequest) (*core.SbpOutgoingResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Process", ctx, domainRequest)
	ret0, _ := ret[0].(*core.SbpOutgoingResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Process indicates an expected call of Process.
func (mr *MockSbpOutgoingOperationsMockRecorder) Process(ctx, domainRequest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Process", reflect.TypeOf((*MockSbpOutgoingOperations)(nil).Process), ctx, domainRequest)
}

// MockInternalOperations is a mock of InternalOperations interface.
type MockInternalOperations struct {
	ctrl     *gomock.Controller
	recorder *MockInternalOperationsMockRecorder
	isgomock struct{}
}

// MockInternalOperationsMockRecorder is the mock recorder for MockInternalOperations.
type MockInternalOperationsMockRecorder struct {
	mock *MockInternalOperations
}

// NewMockInternalOperations creates a new mock instance.
func NewMockInternalOperations(ctrl *gomock.Controller) *MockInternalOperations {
	mock := &MockInternalOperations{ctrl: ctrl}
	mock.recorder = &MockInternalOperationsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInternalOperations) EXPECT() *MockInternalOperationsMockRecorder {
	return m.recorder
}

// Process mocks base method.
func (m *MockInternalOperations) Process(ctx context.Context, domainRequest *model.InternalDomainRequest) (*core.InternalResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Process", ctx, domainRequest)
	ret0, _ := ret[0].(*core.InternalResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Process indicates an expected call of Process.
func (mr *MockInternalOperationsMockRecorder) Process(ctx, domainRequest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Process", reflect.TypeOf((*MockInternalOperations)(nil).Process), ctx, domainRequest)
}

// MockCashInOperations is a mock of CashInOperations interface.
type MockCashInOperations struct {
	ctrl     *gomock.Controller
	recorder *MockCashInOperationsMockRecorder
	isgomock struct{}
}

// MockCashInOperationsMockRecorder is the mock recorder for MockCashInOperations.
type MockCashInOperationsMockRecorder struct {
	mock *MockCashInOperations
}

// NewMockCashInOperations creates a new mock instance.
func NewMockCashInOperations(ctrl *gomock.Controller) *MockCashInOperations {
	mock := &MockCashInOperations{ctrl: ctrl}
	mock.recorder = &MockCashInOperationsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCashInOperations) EXPECT() *MockCashInOperationsMockRecorder {
	return m.recorder
}

// Process mocks base method.
func (m *MockCashInOperations) Process(ctx context.Context, domainRequest *model.CashInDomainRequest) (*core.CashInResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Process", ctx, domainRequest)
	ret0, _ := ret[0].(*core.CashInResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Process indicates an expected call of Process.
func (mr *MockCashInOperationsMockRecorder) Process(ctx, domainRequest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Process", reflect.TypeOf((*MockCashInOperations)(nil).Process), ctx, domainRequest)
}

// MockCashOutOperations is a mock of CashOutOperations interface.
type MockCashOutOperations struct {
	ctrl     *gomock.Controller
	recorder *MockCashOutOperationsMockRecorder
	isgomock struct{}
}

// MockCashOutOperationsMockRecorder is the mock recorder for MockCashOutOperations.
type MockCashOutOperationsMockRecorder struct {
	mock *MockCashOutOperations
}

// NewMockCashOutOperations creates a new mock instance.
func NewMockCashOutOperations(ctrl *gomock.Controller) *MockCashOutOperations {
	mock := &MockCashOutOperations{ctrl: ctrl}
	mock.recorder = &MockCashOutOperationsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCashOutOperations) EXPECT() *MockCashOutOperationsMockRecorder {
	return m.recorder
}

// Process mocks base method.
func (m *MockCashOutOperations) Process(ctx context.Context, domainRequest *model.CashOutDomainRequest) (*core.CashOutResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Process", ctx, domainRequest)
	ret0, _ := ret[0].(*core.CashOutResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Process indicates an expected call of Process.
func (mr *MockCashOutOperationsMockRecorder) Process(ctx, domainRequest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Process", reflect.TypeOf((*MockCashOutOperations)(nil).Process), ctx, domainRequest)
}
