# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import core_pb2 as core__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in core_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CoreStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Internal = channel.unary_unary(
                '/core.Core/Internal',
                request_serializer=core__pb2.InternalRequest.SerializeToString,
                response_deserializer=core__pb2.InternalResponse.FromString,
                _registered_method=True)
        self.SbpOutgoing = channel.unary_unary(
                '/core.Core/SbpOutgoing',
                request_serializer=core__pb2.SbpOutgoingRequest.SerializeToString,
                response_deserializer=core__pb2.SbpOutgoingResponse.FromString,
                _registered_method=True)
        self.CashIn = channel.unary_unary(
                '/core.Core/CashIn',
                request_serializer=core__pb2.CashInRequest.SerializeToString,
                response_deserializer=core__pb2.CashInResponse.FromString,
                _registered_method=True)
        self.CashOut = channel.unary_unary(
                '/core.Core/CashOut',
                request_serializer=core__pb2.CashOutRequest.SerializeToString,
                response_deserializer=core__pb2.CashOutResponse.FromString,
                _registered_method=True)


class CoreServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Internal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SbpOutgoing(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CashIn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CashOut(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Internal': grpc.unary_unary_rpc_method_handler(
                    servicer.Internal,
                    request_deserializer=core__pb2.InternalRequest.FromString,
                    response_serializer=core__pb2.InternalResponse.SerializeToString,
            ),
            'SbpOutgoing': grpc.unary_unary_rpc_method_handler(
                    servicer.SbpOutgoing,
                    request_deserializer=core__pb2.SbpOutgoingRequest.FromString,
                    response_serializer=core__pb2.SbpOutgoingResponse.SerializeToString,
            ),
            'CashIn': grpc.unary_unary_rpc_method_handler(
                    servicer.CashIn,
                    request_deserializer=core__pb2.CashInRequest.FromString,
                    response_serializer=core__pb2.CashInResponse.SerializeToString,
            ),
            'CashOut': grpc.unary_unary_rpc_method_handler(
                    servicer.CashOut,
                    request_deserializer=core__pb2.CashOutRequest.FromString,
                    response_serializer=core__pb2.CashOutResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'core.Core', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('core.Core', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Core(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Internal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.Core/Internal',
            core__pb2.InternalRequest.SerializeToString,
            core__pb2.InternalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SbpOutgoing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.Core/SbpOutgoing',
            core__pb2.SbpOutgoingRequest.SerializeToString,
            core__pb2.SbpOutgoingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CashIn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.Core/CashIn',
            core__pb2.CashInRequest.SerializeToString,
            core__pb2.CashInResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CashOut(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.Core/CashOut',
            core__pb2.CashOutRequest.SerializeToString,
            core__pb2.CashOutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
