// Code generated by MockGen. DO NOT EDIT.
// Source: ./../../pkg/antifraud/antifraud_grpc.pb.go
//
// Generated by this command:
//
//	mockgen -source=./../../pkg/antifraud/antifraud_grpc.pb.go -destination=mocks/antifraud_client_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	antifraud "processing_core/pkg/antifraud"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockOnlineCheckClient is a mock of OnlineCheckClient interface.
type MockOnlineCheckClient struct {
	ctrl     *gomock.Controller
	recorder *MockOnlineCheckClientMockRecorder
	isgomock struct{}
}

// MockOnlineCheckClientMockRecorder is the mock recorder for MockOnlineCheckClient.
type MockOnlineCheckClientMockRecorder struct {
	mock *MockOnlineCheckClient
}

// NewMockOnlineCheckClient creates a new mock instance.
func NewMockOnlineCheckClient(ctrl *gomock.Controller) *MockOnlineCheckClient {
	mock := &MockOnlineCheckClient{ctrl: ctrl}
	mock.recorder = &MockOnlineCheckClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOnlineCheckClient) EXPECT() *MockOnlineCheckClientMockRecorder {
	return m.recorder
}

// CashOut mocks base method.
func (m *MockOnlineCheckClient) CashOut(ctx context.Context, in *antifraud.Transaction, opts ...grpc.CallOption) (*antifraud.CheckResult, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CashOut", varargs...)
	ret0, _ := ret[0].(*antifraud.CheckResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CashOut indicates an expected call of CashOut.
func (mr *MockOnlineCheckClientMockRecorder) CashOut(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CashOut", reflect.TypeOf((*MockOnlineCheckClient)(nil).CashOut), varargs...)
}

// Internal mocks base method.
func (m *MockOnlineCheckClient) Internal(ctx context.Context, in *antifraud.Transaction, opts ...grpc.CallOption) (*antifraud.CheckResult, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Internal", varargs...)
	ret0, _ := ret[0].(*antifraud.CheckResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Internal indicates an expected call of Internal.
func (mr *MockOnlineCheckClientMockRecorder) Internal(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Internal", reflect.TypeOf((*MockOnlineCheckClient)(nil).Internal), varargs...)
}

// SbpOutgoing mocks base method.
func (m *MockOnlineCheckClient) SbpOutgoing(ctx context.Context, in *antifraud.Transaction, opts ...grpc.CallOption) (*antifraud.CheckResult, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SbpOutgoing", varargs...)
	ret0, _ := ret[0].(*antifraud.CheckResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SbpOutgoing indicates an expected call of SbpOutgoing.
func (mr *MockOnlineCheckClientMockRecorder) SbpOutgoing(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SbpOutgoing", reflect.TypeOf((*MockOnlineCheckClient)(nil).SbpOutgoing), varargs...)
}

// MockOnlineCheckServer is a mock of OnlineCheckServer interface.
type MockOnlineCheckServer struct {
	ctrl     *gomock.Controller
	recorder *MockOnlineCheckServerMockRecorder
	isgomock struct{}
}

// MockOnlineCheckServerMockRecorder is the mock recorder for MockOnlineCheckServer.
type MockOnlineCheckServerMockRecorder struct {
	mock *MockOnlineCheckServer
}

// NewMockOnlineCheckServer creates a new mock instance.
func NewMockOnlineCheckServer(ctrl *gomock.Controller) *MockOnlineCheckServer {
	mock := &MockOnlineCheckServer{ctrl: ctrl}
	mock.recorder = &MockOnlineCheckServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOnlineCheckServer) EXPECT() *MockOnlineCheckServerMockRecorder {
	return m.recorder
}

// CashOut mocks base method.
func (m *MockOnlineCheckServer) CashOut(arg0 context.Context, arg1 *antifraud.Transaction) (*antifraud.CheckResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CashOut", arg0, arg1)
	ret0, _ := ret[0].(*antifraud.CheckResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CashOut indicates an expected call of CashOut.
func (mr *MockOnlineCheckServerMockRecorder) CashOut(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CashOut", reflect.TypeOf((*MockOnlineCheckServer)(nil).CashOut), arg0, arg1)
}

// Internal mocks base method.
func (m *MockOnlineCheckServer) Internal(arg0 context.Context, arg1 *antifraud.Transaction) (*antifraud.CheckResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Internal", arg0, arg1)
	ret0, _ := ret[0].(*antifraud.CheckResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Internal indicates an expected call of Internal.
func (mr *MockOnlineCheckServerMockRecorder) Internal(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Internal", reflect.TypeOf((*MockOnlineCheckServer)(nil).Internal), arg0, arg1)
}

// SbpOutgoing mocks base method.
func (m *MockOnlineCheckServer) SbpOutgoing(arg0 context.Context, arg1 *antifraud.Transaction) (*antifraud.CheckResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SbpOutgoing", arg0, arg1)
	ret0, _ := ret[0].(*antifraud.CheckResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SbpOutgoing indicates an expected call of SbpOutgoing.
func (mr *MockOnlineCheckServerMockRecorder) SbpOutgoing(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SbpOutgoing", reflect.TypeOf((*MockOnlineCheckServer)(nil).SbpOutgoing), arg0, arg1)
}

// mustEmbedUnimplementedOnlineCheckServer mocks base method.
func (m *MockOnlineCheckServer) mustEmbedUnimplementedOnlineCheckServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedOnlineCheckServer")
}

// mustEmbedUnimplementedOnlineCheckServer indicates an expected call of mustEmbedUnimplementedOnlineCheckServer.
func (mr *MockOnlineCheckServerMockRecorder) mustEmbedUnimplementedOnlineCheckServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedOnlineCheckServer", reflect.TypeOf((*MockOnlineCheckServer)(nil).mustEmbedUnimplementedOnlineCheckServer))
}

// MockUnsafeOnlineCheckServer is a mock of UnsafeOnlineCheckServer interface.
type MockUnsafeOnlineCheckServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeOnlineCheckServerMockRecorder
	isgomock struct{}
}

// MockUnsafeOnlineCheckServerMockRecorder is the mock recorder for MockUnsafeOnlineCheckServer.
type MockUnsafeOnlineCheckServerMockRecorder struct {
	mock *MockUnsafeOnlineCheckServer
}

// NewMockUnsafeOnlineCheckServer creates a new mock instance.
func NewMockUnsafeOnlineCheckServer(ctrl *gomock.Controller) *MockUnsafeOnlineCheckServer {
	mock := &MockUnsafeOnlineCheckServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeOnlineCheckServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeOnlineCheckServer) EXPECT() *MockUnsafeOnlineCheckServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedOnlineCheckServer mocks base method.
func (m *MockUnsafeOnlineCheckServer) mustEmbedUnimplementedOnlineCheckServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedOnlineCheckServer")
}

// mustEmbedUnimplementedOnlineCheckServer indicates an expected call of mustEmbedUnimplementedOnlineCheckServer.
func (mr *MockUnsafeOnlineCheckServerMockRecorder) mustEmbedUnimplementedOnlineCheckServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedOnlineCheckServer", reflect.TypeOf((*MockUnsafeOnlineCheckServer)(nil).mustEmbedUnimplementedOnlineCheckServer))
}
