// Code generated by MockGen. DO NOT EDIT.
// Source: settings.go
//
// Generated by this command:
//
//	mockgen -source=settings.go -destination=./mocks/feature_store_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	constants "antifraud/internal/constants"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFeatureStore is a mock of FeatureStore interface.
type MockFeatureStore struct {
	ctrl     *gomock.Controller
	recorder *MockFeatureStoreMockRecorder
	isgomock struct{}
}

// MockFeatureStoreMockRecorder is the mock recorder for MockFeatureStore.
type MockFeatureStoreMockRecorder struct {
	mock *MockFeatureStore
}

// NewMockFeatureStore creates a new mock instance.
func NewMockFeatureStore(ctrl *gomock.Controller) *MockFeatureStore {
	mock := &MockFeatureStore{ctrl: ctrl}
	mock.recorder = &MockFeatureStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeatureStore) EXPECT() *MockFeatureStoreMockRecorder {
	return m.recorder
}

// GetFeatureInteger mocks base method.
func (m *MockFeatureStore) GetFeatureInteger(ctx context.Context, featureID constants.FeatureType, featureFilter *constants.FeatureFilter) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFeatureInteger", ctx, featureID, featureFilter)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFeatureInteger indicates an expected call of GetFeatureInteger.
func (mr *MockFeatureStoreMockRecorder) GetFeatureInteger(ctx, featureID, featureFilter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFeatureInteger", reflect.TypeOf((*MockFeatureStore)(nil).GetFeatureInteger), ctx, featureID, featureFilter)
}

// GetFeatureString mocks base method.
func (m *MockFeatureStore) GetFeatureString(ctx context.Context, featureID constants.FeatureType, featureFilter *constants.FeatureFilter) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFeatureString", ctx, featureID, featureFilter)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFeatureString indicates an expected call of GetFeatureString.
func (mr *MockFeatureStoreMockRecorder) GetFeatureString(ctx, featureID, featureFilter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFeatureString", reflect.TypeOf((*MockFeatureStore)(nil).GetFeatureString), ctx, featureID, featureFilter)
}
